// main.js
import { app, shell, BrowserWindow, ipcMain, session } from 'electron'
import { join } from 'path'
import { electronApp, optimizer, is, } from '@electron-toolkit/utils'
import icon from '../../resources/icon.png?asset'
import { writeFileSync, readFileSync,unlinkSync } from 'fs'

import ffmpeg from '@ffmpeg-installer/ffmpeg';
import ffmpegFluent from 'fluent-ffmpeg';
const { exec } = require('child_process')
ffmpegFluent.setFfmpegPath(ffmpeg.path);
// Path to your cookies.txt
const cookiesPath = app.isPackaged
  ? join(process.resourcesPath, 'cookies.txt')
  : join(__dirname, '../../public/cookies.txt')

// Path to yt-dlp
const ytdlpPath = app.isPackaged
  ? join(process.resourcesPath, 'yt-dlp.exe')
  : join(__dirname, '../../public/yt-dlp.exe')

// Helper to update cookies.txt
async function updateCookiesFile() {
  try {
    const cookies = await session.defaultSession.cookies.get({ domain: '.youtube.com' })

    if (!cookies.length) {
      console.error('No YouTube cookies found.')
      return
    }

    // Build a header line recognized by yt-dlp.
    const lines = [
      '# Netscape HTTP Cookie File',
      '# This file is generated by Electron for use by yt-dlp.',
      '# This file was last updated on ' + new Date().toString(),
      '' // blank line after header
    ]

    // Convert each cookie to a proper Netscape line
    // Fields (tab-separated):
    // domain, include_subdomains, path, secure, expiration, name, value
    cookies.forEach((cookie) => {
      // Example: If the domain is "youtube.com" and you want to cover subdomains, prefix it with a dot.
      // But if it's already something like ".youtube.com", leave it.
      let domain = cookie.domain
      if (!domain.startsWith('.')) {
        // In many official examples, you only do this if you want subdomains = TRUE
        domain = '.' + domain
      }

      // Force "TRUE" if we want subdomains. If you only want EXACT domain matching, use "FALSE".
      const includeSubdomains = 'TRUE'

      // Some cookies from YouTube might be secure, some not. Typically you can do:
      const isSecure = cookie.secure ? 'TRUE' : 'FALSE'

      // expiry (seconds) or 0 if session cookie
      const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0

      // Construct the line
      // Typically these fields are tab-separated. Some tools are okay with spaces, but
      // `yt-dlp` is most consistent if you use a single tab between fields.
      const line = [
        domain,
        includeSubdomains,
        cookie.path,
        isSecure,
        expiry,
        cookie.name,
        cookie.value
      ].join('\t')

      lines.push(line)
    })

    // Join all lines with \n
    const fileContent = lines.join('\n')

    writeFileSync(cookiesPath, fileContent, 'utf8')
    console.log('Cookies updated successfully at:', cookiesPath)
  } catch (error) {
    console.error('Error updating cookies:', error)
  }
}

function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 900,
    height: 670,
    show: false,
    autoHideMenuBar: true,
    ...(process.platform === 'linux' ? { icon } : {}),
    webPreferences: {
      webviewTag: false,
      nativeWindowOpen: true,
      nodeIntegration: true, // or false, depending on your needs
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false
    }
  })

  mainWindow.on('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

app.whenReady().then(() => {
  electronApp.setAppUserModelId('com.electron')

  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })

  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

// -------------------------------------
// Open a webview for YouTube
// -------------------------------------
ipcMain.on('open-webview', (event, url) => {
  let webviewWindow = new BrowserWindow({
    height: 600,
    webPreferences: {
      webviewTag: true,
      nodeIntegration: false,
      contextIsolation: true
    }
  })

  webviewWindow.loadURL(url)

  // 1) For full navigations:
  webviewWindow.webContents.on('did-navigate', async (e, navigationUrl) => {
    if (navigationUrl.includes('youtube.com')) {
      await updateCookiesFile()
    }
  })

  // 2) For in-page navigations (like clicking a new video without a full reload)
  webviewWindow.webContents.on('did-navigate-in-page', async (e, navigationUrl) => {
    if (navigationUrl.includes('youtube.com')) {
      await updateCookiesFile()
    }
  })

  webviewWindow.on('closed', () => {
    webviewWindow = null
  })
})

// -------------------------------------
// Download video with yt-dlp
// -------------------------------------
ipcMain.handle('downloadVideo', async (event, url, videoFormat, audioFormat) => {
  console.log("Selected Video Format:", videoFormat);
  console.log("Selected Audio Format:", audioFormat);

  return new Promise((resolve, reject) => {
    const downloadDir = app.getPath('downloads');

    // Step 1: Retrieve original filename
    const getFilenameCommand = `"${ytdlpPath}" --get-filename -o "%(title)s" "${url}"`;

    exec(getFilenameCommand, (error, stdout) => {
      if (error) {
        console.error('Error getting filename:', error);
        return reject("Failed to retrieve filename");
      }

      const filename = stdout.trim(); // Extract filename without extension
      const videoPath = join(downloadDir, `${filename}_video.mp4`);
      const audioPath = join(downloadDir, `${filename}_audio.m4a`);
      const outputPath = join(downloadDir, `${filename}.mp4`);

      // Step 2: Download video and audio separately
      const videoCommand = `"${ytdlpPath}" -f ${videoFormat} -o "${videoPath}" "${url}"`;
      const audioCommand = `"${ytdlpPath}" -f ${audioFormat} -o "${audioPath}" "${url}"`;

      exec(videoCommand, (videoError) => {
        if (videoError) return reject('Failed to download video');

        exec(audioCommand, (audioError) => {
          if (audioError) return reject('Failed to download audio');

          // Step 3: Merge video and audio
          mergeVideoAudio(videoPath, audioPath, outputPath)
            .then(() => {
              // Step 4: Delete temporary files after merging
              try {
                unlinkSync(videoPath);
                unlinkSync(audioPath);
              } catch (err) {
                console.error("Error deleting temporary files:", err);
              }
              resolve(outputPath);
            })
            .catch((err) => reject(err));
        });
      });
    });
  });
});

// 🎥 Merge Video & Audio using FFmpeg
function mergeVideoAudio(videoPath, audioPath, outputPath) {
  console.log("Merging:", videoPath, " + ", audioPath);

  return new Promise((resolve, reject) => {
    ffmpegFluent()
      .input(videoPath)
      .input(audioPath)
      .outputOptions('-c:v copy')
      .outputOptions('-c:a aac')
      .outputOptions('-strict experimental') // Ensures compatibility
      .save(outputPath)
      .on('end', () => resolve(outputPath))
      .on('error', (err) => reject(`Merge error: ${err.message}`));
  });
}

// -------------------------------------
// Force update & retrieve path of cookies
// -------------------------------------
ipcMain.handle('getYoutubeCookies', async () => {
  await updateCookiesFile()
  return cookiesPath
})

// -------------------------------------
// Get formats from JSON file
// -------------------------------------
const formatsFile = join(__dirname, '../../public/formats.json')
// const availableFormats = JSON.parse(readFileSync(formatsFile, 'utf8'))

// ipcMain.handle('getFormats', async () => {
//   return availableFormats
// })
ipcMain.handle('getFormats', async (event, url) => {
  console.log("url",url);
  
  return new Promise((resolve, reject) => {
    const command = `"${ytdlpPath}" -F "${url}"`;

    exec(command, (error, stdout, stderr) => {
      if (error) {
        console.error('Error fetching formats:', stderr);
        reject("Failed to fetch formats");
      } else {
        const formats = parseFormats(stdout);
       // Debugging
        resolve(formats);
      }
    });
  });
});

// Function to only return 720p, 1080p, and two audio formats
function parseFormats(output) {
  return output.split('\n').map((line) => {
    const match = line.match(/^(\d+)\s+(\w+)\s+(\d+x\d+|\d+kbps|audio only)/);
    return match ? { formatId: match[1], formatType: match[2], quality: match[3] } : null;
  }).filter(Boolean);
}
