import { app, shell, BrowserWindow, ipcMain, session } from 'electron'
import { join } from 'path'
import { electronApp, optimizer, is } from '@electron-toolkit/utils'
import linuxIcon from '../../resources/icon.png?asset'
import { writeFileSync, unlinkSync, existsSync, mkdirSync } from 'fs'

import ffmpeg from '@ffmpeg-installer/ffmpeg'
import ffmpegFluent from 'fluent-ffmpeg'
import { spawn } from 'child_process'

ffmpegFluent.setFfmpegPath(ffmpeg.path)
let iconPath = ''
switch (process.platform) {
  case 'win32':
    iconPath = join(__dirname, '../../public/icon.ico')
    break
  case 'linux':
    iconPath = linuxIcon
    break
  default:
    iconPath = join(process.resourcesPath, 'icon.png')
}
console.log('Using iconPath:', iconPath)
const ffmpegPath = ffmpeg.path
const cookiesPath = app.isPackaged
  ? join(process.resourcesPath, 'cookies.txt')
  : join(__dirname, '../../public/cookies.txt')

const ytdlpPath = app.isPackaged
  ? join(process.resourcesPath, 'yt-dlp.exe')
  : join(__dirname, '../../public/yt-dlp.exe')

// Helper to update cookies.txt
async function updateCookiesFile() {
  try {
    const cookies = await session.defaultSession.cookies.get({ domain: '.youtube.com' })
    if (!cookies.length) {
      console.error('No YouTube cookies found.')
      return
    }

    const lines = [
      '# Netscape HTTP Cookie File',
      '# This file is generated by Electron for use by yt-dlp.',
      '# This file was last updated on ' + new Date().toString(),
      ''
    ]

    cookies.forEach((cookie) => {
      let domain = cookie.domain
      if (!domain.startsWith('.')) {
        domain = '.' + domain
      }
      const includeSubdomains = 'TRUE'
      const isSecure = cookie.secure ? 'TRUE' : 'FALSE'
      const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0

      const line = [
        domain,
        includeSubdomains,
        cookie.path,
        isSecure,
        expiry,
        cookie.name,
        cookie.value
      ].join('\t')

      lines.push(line)
    })

    const fileContent = lines.join('\n')
    writeFileSync(cookiesPath, fileContent, 'utf8')
    console.log('Cookies updated successfully at:', cookiesPath)
  } catch (error) {
    console.error('Error updating cookies:', error)
  }
}

function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 900,
    height: 670,
    show: false,
    autoHideMenuBar: true,
    icon: iconPath,

    webPreferences: {
      webviewTag: false,
      nativeWindowOpen: true,
      nodeIntegration: true,
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false
    }
  })

  mainWindow.on('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

app.whenReady().then(() => {
  electronApp.setAppUserModelId('com.electron')
  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

// -------------------------------------
// Open a webview for YouTube
// -------------------------------------
ipcMain.on('open-webview', (event, url) => {
  let webviewWindow = new BrowserWindow({
    height: 600,
    webPreferences: {
      webviewTag: true,
      nodeIntegration: false,
      contextIsolation: true
    }
  })

  webviewWindow.loadURL(url)

  // 1) For full navigations:
  webviewWindow.webContents.on('did-navigate', async (e, navigationUrl) => {
    if (navigationUrl.includes('youtube.com')) {
      await updateCookiesFile()
    }
  })

  // 2) For in-page navigations
  webviewWindow.webContents.on('did-navigate-in-page', async (e, navigationUrl) => {
    if (navigationUrl.includes('youtube.com')) {
      await updateCookiesFile()
    }
  })

  webviewWindow.on('closed', () => {
    webviewWindow = null
  })
})

// -------------------------------------
// Download video with yt-dlp + progress
// -------------------------------------
ipcMain.handle('downloadVideo', async (event, options) => {
  try {
    const { url, isAudioOnly, selectedFormat, selectedQuality } = options

    // Decide on a download folder
    const downloadDir = app.getPath('downloads')
    if (!existsSync(downloadDir)) {
      mkdirSync(downloadDir, { recursive: true })
    }

    // Provide a fallback if selectedQuality is undefined
    const finalQuality = selectedQuality || '720'
    const finalFormat = selectedFormat?.toLowerCase() || 'mp4'

    // 1) Build the format specifier:
    let formatSpecifier
    if (isAudioOnly) {
      // Example: force MP3, highest quality
      // or use user’s chosen format + quality
      formatSpecifier = `--extract-audio --audio-format ${finalFormat} --audio-quality ${finalQuality}`
    } else {
      // Example: -f "mp4[height<=720]+bestaudio" or fallback to best
      formatSpecifier = `-f ${finalFormat}[height<=${finalQuality}]+bestaudio/${finalFormat}+bestaudio/best`
    }

    // 2) Output template 
    //    Using a combination of flags to sanitize file names.
    const outputTemplate = `${downloadDir}/%(title)s.%(ext)s`

    // 3) Build the spawn arguments
    const args = [
      ...formatSpecifier.split(' '),
      '--ffmpeg-location', ffmpegPath,
      '--cookies', cookiesPath, 
      '--embed-metadata',
      '--embed-thumbnail',
      '--restrict-filenames',
      '--windows-filenames',
      '-o', outputTemplate,
      url,
      '--newline',        // So we can parse progress line by line
      '--ignore-errors',
      '--no-warnings',
      '--ignore-config',
      '--no-simulate',
      '--quiet',
      '--progress',
      '--print', 'title',      // optional
      '--print', 'thumbnail'   // optional
      // '--no-playlist',      // if you want to avoid playlist downloads
    ]

    // 4) Actually spawn yt-dlp
    const proc = spawn(ytdlpPath, args)

    return await new Promise((resolve, reject) => {
      let stdoutData = ''
      let stderrData = ''

      proc.stdout.on('data', (data) => {
        const line = data.toString().trim()
        stdoutData += line + '\n'

        // Simple regex to parse progress lines like:
        // [download]   0.2% of 3.05MiB at 402.74KiB/s ETA 00:07
        const regex = /\[download\]\s+([\d.]+)% of ([\d.]+\w+) at\s+([\d.]+\w+\/s)\s+ETA\s+([\d:]+)/

        const match = line.match(regex)
        if (match) {
          const progress = parseFloat(match[1]) || 0
          const fileSize = match[2] || ''
          const speed = match[3] || ''
          const eta = match[4] || ''

          // Send progress to renderer
          event.sender.send('download-progress', {
            progress,
            fileSize,
            speed,
            eta,
            status: isAudioOnly ? 'Downloading audio...' : 'Downloading video...',
            file: outputTemplate
          })
        }
      })

      proc.stderr.on('data', (data) => {
        const line = data.toString().trim()
        stderrData += line + '\n'
        console.error('[yt-dlp stderr]', line)
      })

      proc.on('close', (code) => {
        if (code === 0) {
          // Possibly send a final 100% event
          event.sender.send('download-progress', {
            progress: 100,
            fileSize: '',
            speed: '',
            eta: '',
            status: 'Download complete!',
            file: outputTemplate
          })
          resolve(outputTemplate)
        } else {
          reject(new Error(`yt-dlp exited with code ${code}.\n${stderrData}`))
        }
      })
    })
  } catch (err) {
    console.error('downloadVideo error:', err)
    throw err
  }
})

// -------------------------------------
// Retrieve original filename
// Using spawn + parse stdout
// -------------------------------------
function getFilename(url) {
  return new Promise((resolve, reject) => {
    const args = ['--get-filename', '-o', '%(title)s', url]
    const proc = spawn(ytdlpPath, args)

    let stdout = ''
    let stderr = ''

    proc.stdout.on('data', (data) => {
      stdout += data.toString()
    })

    proc.stderr.on('data', (data) => {
      stderr += data.toString()
    })

    proc.on('close', (code) => {
      if (code === 0) {
        resolve(stdout.trim())
      } else {
        reject(new Error(`getFilename failed: ${stderr}`))
      }
    })
  })
}

// -------------------------------------
// Download with progress
// Pass in either video/audio format + path
// -------------------------------------
function downloadWithProgress(event, url, format, outputPath, stage) {
  return new Promise((resolve, reject) => {
    // Example: yt-dlp -f <format> -o <path> <url>
    const args = ['-f', format, '-o', outputPath, url, '--newline', '--progress']
    const proc = spawn(ytdlpPath, args)

    proc.stdout.on('data', (data) => {
      const line = data.toString().trim()
      // Optional: parse progress lines from yt-dlp
      // They often look like:
      // [download]   0.2% of 3.05MiB at 402.74KiB/s ETA 00:07

      // A quick regex to capture relevant data:
      const regex = /\[download\]\s+([\d.]+)% of ([\d.]+\w+) at\s+([\d.]+\w+\/s)\s+ETA\s+([\d:]+)/

      if (regex.test(line)) {
        const match = line.match(regex)
        if (match) {
          const progress = parseFloat(match[1]) || 0
          const fileSize = match[2] || ''
          const speed = match[3] || ''
          const eta = match[4] || ''

          event.sender.send('download-progress', {
            progress,
            fileSize,
            speed,
            eta,
            status: `${stage} downloading...`,
            file: outputPath
          })
        }
      }
    })

    proc.stderr.on('data', (data) => {
      console.error(`yt-dlp ${stage} stderr:`, data.toString())
    })

    proc.on('close', (code) => {
      if (code === 0) {
        resolve()
      } else {
        reject(new Error(`yt-dlp ${stage} download failed with code ${code}`))
      }
    })
  })
}

// -------------------------------------
// Merge with ffmpeg & send optional progress
// -------------------------------------
function mergeVideoAudio(event, videoPath, audioPath, outputPath) {
  return new Promise((resolve, reject) => {
    ffmpegFluent()
      .input(videoPath)
      .input(audioPath)
      .outputOptions('-c:v copy')
      .outputOptions('-c:a aac')
      .outputOptions('-strict experimental')
      .on('progress', (info) => {
        // FFmpeg progress is different from yt-dlp's.
        // You only get an approximate "frames" or "time" object
        // You can compute approximate percentage if you know total duration.
        // For simplicity, we’ll just send a “merging in progress” message:
        event.sender.send('download-progress', {
          progress: 99, // or keep it separate from the main progress
          fileSize: '',
          speed: '',
          eta: '',
          status: `Merging...`,
          file: outputPath
        })
      })
      .on('end', () => {
        resolve(outputPath)
      })
      .on('error', (err) => {
        reject(`Merge error: ${err.message}`)
      })
      .save(outputPath)
  })
}

function safeUnlink(path) {
  try {
    if (existsSync(path)) {
      unlinkSync(path)
    }
  } catch (e) {
    console.warn(`Failed to remove temp file: ${path}`, e)
  }
}

// -------------------------------------
// Force update & retrieve path of cookies
// -------------------------------------
ipcMain.handle('getYoutubeCookies', async () => {
  await updateCookiesFile()
  return cookiesPath
})

// -------------------------------------
// Dynamically fetch formats via yt-dlp -F
// -------------------------------------
ipcMain.handle('getFormats', async (event, url) => {
  return new Promise((resolve, reject) => {
    const args = ['-F', url]
    const proc = spawn(ytdlpPath, args)

    let stdout = ''
    let stderr = ''

    proc.stdout.on('data', (data) => {
      stdout += data.toString()
    })

    proc.stderr.on('data', (data) => {
      stderr += data.toString()
    })

    proc.on('close', (code) => {
      if (code !== 0) {
        console.error('Error fetching formats:', stderr)
        return reject("Failed to fetch formats")
      } else {
        const formats = parseFormats(stdout)
        resolve(formats)
      }
    })
  })
})

// Only return the lines that match a typical "ID EXT RES/bitrate" pattern
function parseFormats(output) {
  return output
    .split('\n')
    .map((line) => {
      // Example lines from "yt-dlp -F"
      // 18 mp4  640x360
      // 22 mp4  1280x720
      // 140 m4a audio only
      const match = line.match(/^(\d+)\s+(\w+)\s+(\S+)/)
      if (!match) return null

      const formatId = match[1]
      const formatType = match[2]
      const quality = match[3] // could be resolution or "audio only"

      return { formatId, formatType, quality }
    })
    .filter(Boolean)
}
